package poesia;
// Generated 12 dic 2023 14:58:22 by Hibernate Tools 6.3.1.Final

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {
    private Long id;
	private int alumno;
	private String nombre;
	private String nacionalidad;
	private int edad;

	public Alumnos() {
	}

	public Alumnos(int alumno, String nombre, String nacionalidad, int edad) {
		this.alumno = alumno;
		this.nombre = nombre;
		this.nacionalidad = nacionalidad;
		this.edad = edad;
	}

    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public int getAlumno() {
		return this.alumno;
	}

	public void setAlumno(int alumno) {
		this.alumno = alumno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

}
